Repository MajorcaDevs/mdbackup, pull requests merged in 2019-02, with the labels that each got.

#2 Backblaze intergration
  mdbackup/__main__.py
  mdbackup/backup.py
  mdbackup/config.py
  mdbackup/storage/backblaze.py
  mdbackup/storage/s3.py
  mdbackup/utils.sh
  setup.py
Labels: cloud-provider, enhancement

#1 Secret providers
  README.md
  config/config.schema.json
  mdbackup/__main__.py
  mdbackup/config.py
  mdbackup/secrets/file_backend.py
  mdbackup/secrets/secrets.py
  mdbackup/secrets/vault_backend.py
Labels: enhancement, secret-provider

#4 Follow symlinks when uploading backups
  mdbackup/__main__.py
Labels: bug

#3 Backup files utils
  README.md
  mdbackup/utils.sh
Labels: bash-scripts, enhancement

#6 Added support to run parts of the tool
  README.md
  mdbackup/__main__.py
  mdbackup/backup.py
Labels: enhancement

#5 Optional dependencies
  README.md
  mdbackup/__main__.py
  mdbackup/archive.py
  mdbackup/check_packages/__init__.py
  mdbackup/config.py
  mdbackup/secrets/__init__.py
  mdbackup/secrets/file_backend.py
  mdbackup/secrets/vault_backend.py
  mdbackup/storage/__init__.py
  mdbackup/storage/backblaze.py
  mdbackup/storage/drive.py
  mdbackup/storage/s3.py
  mdbackup/utils.sh
  setup.py
Labels: bash-scripts, bug, cloud-provider, enhancement, secret-provider

#7 Debug info from bash scripts and realtime logs from them
  mdbackup/backup.py
  mdbackup/utils.sh
Labels: bash-scripts, bug, enhancement

#10 #8 Credentials are not handled properly on postgres backups
  mdbackup/backup.py
  mdbackup/utils.sh
Labels: bash-scripts, bug
