Repository MajorcaDevs/mdbackup, pull requests merged in 2020-07, with the labels that each got.

#79 fix: avoid crash when uploading backup with a failed task
  mdbackup/_commands/backup.py
  mdbackup/_commands/upload.py
  mdbackup/actions/builtin/file.py
Labels: bug

#80 Docs/fixes for latest changes in mkdocs material
  docs/actions/network.md
  docs/configuration.md
  docs/docker/version-menu.js
  docs/quick-start.md
  docs/tasks.md
  mkdocs.yml
Labels: docs

#82 Fix: docs publishing
  jenkins/dev-master.jenkinsfile
  mkdocs.yml
Labels: CI/CD

#84 Fix #83 - Disable user param when calling psql action with docker
  mdbackup/actions/builtin/database.py
Labels: bug
